### ISSUE TITLE
Roles and RoleBindings get created 2 times

### ISSUE THREAD

**Issue by ChristianRaoulis** [caas-team/caas-project-monitoring#40]
When i try to deploy the helm chart on caas i run into an error due to the "already existing"  Roles and RoleBindings.

<details>

<summary>My values.yaml</summary>

```yaml
# Default values for caas kube-prometheus-stack.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

caas:
  # create a namespaces ServiceAccount
  rbac:
    enabled: true
    serviceAccount:
      create: true
      name: project-monitoring
  # list of additional namespaces where project-monitoring should watch
  projectNamespaces: "core-services monitoring-services"
  #projectNamespaces: demoapp3 demoapp4
  #
  # deploy additional nginx.conf and dashboard for Grafana
  grafana:
    configmaps: true
  fullnameOverride: ""
  nameOverride: ""
  # overrides the default namespace for caas related resources
  namespaceOverride: ""
  #
  # patch job to set securityContect in Prometheus/Alertmanager statefulset
  patchjob:
    enabled: false
    image:
      repository: mtr.devops.telekom.de/caas/kubectl
      tag: latest
    pullPolicy: IfNotPresent
    # minimal permissions for pod
    podSecurityContext:
      fsGroup: 1000
      supplementalGroups:
        - 1000
    # resources for kubectl job
    resources:
      requests:
        cpu: 1m
        memory: 8Mi
      limits:
        cpu: 100m
        memory: 128Mi
    # minimal permissions for container
    securityContext:
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsUser: 1000
      runAsGroup: 1000

global:
  cattle:
    # set clusterId for Grafana reachable via RancherProxy (not necessary in deployment via App store)
    #clusterId: c-xxxxx
    # projectId: &projectId p-xxxxx
    projectId: &projectId <my-project-id>
    systemDefaultRegistry: ""
  imageRegistry: mtr.devops.telekom.de
  imagePullSecrets:
    - mtr-pull-secret

kube-prometheus-stack:
  crds:
    # Only create CRDs if you're a cluster admin.
    create: false
  #  full set of values and pre-defined for caas
  #  ref: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
  nameOverride: "project-monitoring"
  fullnameOverride: "project-monitoring"
  #commonLabels:
  #  field.cattle.io/projectId: *projectId

  ## Create default rules for monitoring the cluster
  ##
  defaultRules:
    create: true
    rules:
      alertmanager: true
      etcd: false
      configReloaders: true
      general: true
      k8s: true
      kubeApiserverAvailability: false
      kubeApiserverBurnrate: false
      kubeApiserverHistogram: false
      kubeApiserverSlos: false
      kubeControllerManager: false
      kubelet: false
      kubeProxy: false
      kubePrometheusGeneral: true
      kubePrometheusNodeRecording: false
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      kubeScheduler: false
      kubeStateMetrics: true
      network: true
      node: false
      nodeExporterAlerting: false
      nodeExporterRecording: false
      prometheus: true
      prometheusOperator: false
    appNamespacesTarget: ".*"
    runbookUrl: "https://runbooks.prometheus-operator.dev/runbooks"
    ## Disabled PrometheusRule alerts
    disabled:
      KubeletDown: true
    # KubeAPIDown: true
    # NodeRAIDDegraded: true
  ## Provide custom recording or alerting rules to be deployed into the cluster.
  ##
  alertmanager:
    apiVersion: v2
    enabled: true
    config:
      global:
        resolve_timeout: 5m
      inhibit_rules:
        - source_matchers:
            - "severity = critical"
          target_matchers:
            - "severity =~ warning|info"
          equal:
            - "namespace"
            - "alertname"
        - source_matchers:
            - "severity = warning"
          target_matchers:
            - "severity = info"
          equal:
            - "namespace"
            - "alertname"
        - source_matchers:
            - "alertname = InfoInhibitor"
          target_matchers:
            - "severity = info"
          equal:
            - "namespace"
      route:
        group_by: ["namespace"]
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: "null"
        routes:
          - receiver: "null"
            matchers:
              - alertname =~ "InfoInhibitor|Watchdog"
      receivers:
        - name: "null"
      templates:
        - "/etc/alertmanager/config/*.tmpl"
    serviceAccount:
      create: true
    service:
      annotations: {}
      labels: {}
      clusterIP: ""
      port: 9093
      targetPort: 9093
      externalIPs: []
      loadBalancerIP: ""
      loadBalancerSourceRanges: []
      externalTrafficPolicy: Cluster
      type: ClusterIP
    servicePerReplica:
      enabled: false
    serviceMonitor:
      interval: "30s"
      selfMonitor: true
    templateFiles:
      rancher_defaults.tmpl: >-
        {{- define "slack.rancher.text" -}}

        {{ template "rancher.text_multiple" . }}

        {{- end -}}

        {{- define "webex.text_multiple" -}}

        {{- range .Alerts }}

        {{ template "webex.text_single" . }}

        {{- end }}

        {{- if .ExternalURL }}

        AlertManager: <{{ .ExternalURL }}>
        
        {{- end }}

        {{- end -}}

        {{- define "webex.text_single" -}}

        {{- if .Labels.alertname }}

        ## [ALERT - {{ .Labels.alertname }}]

        {{- else }}

        ## [ALERT]

        {{- end }}

        {{- if .Labels.severity }}

        ### Severity: `{{ .Labels.severity }}`

        {{- end }}

        {{- if .Labels.cluster }}

        ### Cluster:  {{ .Labels.cluster }}

        {{- end }}

        {{- if .Annotations.summary }}

        ### Summary: {{ .Annotations.summary }}

        {{- end }}

        {{- if .Annotations.message }}

        Message:  {{ .Annotations.message }}

        {{- end }}

        {{- if .Annotations.description }}

        Description:  {{ .Annotations.description }}

        {{- end }}

        {{- if .Annotations.runbook_url }}

        Runbook URL: <{{ .Annotations.runbook_url }}|:spiral_note_pad:>

        {{- end }}

        {{- with .Labels }}

        {{- with .Remove (stringSlice "alertname" "severity" "cluster") }}

        {{- if gt (len .) 0 }}

        Additional Labels:
          {{- range .SortedPairs }}
          • {{ .Name }}: `{{ .Value }}`
          {{- end }}
        {{- end }}

        {{- end }}

        {{- end }}

        {{- with .Annotations }}

        {{- with .Remove (stringSlice "summary" "message" "description"
        "runbook_url") }}

        {{- if gt (len .) 0 }}

        ## Additional Annotations:*
          {{- range .SortedPairs }}
          • {{ .Name }}: `{{ .Value }}`
          {{- end }}
        {{- end }}

        {{- end }}

        {{- end }}


        {{- end -}}

        {{- define "rancher.text_multiple" -}}

        *[GROUP - Details]* 

        One or more alarms in this group have triggered a notification.


        {{- if gt (len .GroupLabels.Values) 0 }}

        *Group Labels:*
          {{- range .GroupLabels.SortedPairs }}
          • *{{ .Name }}:* `{{ .Value }}`
          {{- end }}
        {{- end }}

        {{- if .ExternalURL }}

        *Link to AlertManager:* {{ .ExternalURL }}

        {{- end }}


        {{- range .Alerts }}

        {{ template "rancher.text_single" . }}

        {{- end }}

        {{- end -}}


        {{- define "rancher.text_single" -}}

        {{- if .Labels.alertname }}

        *[ALERT - {{ .Labels.alertname }}]*

        {{- else }}

        *[ALERT]*

        {{- end }}

        {{- if .Labels.severity }}

        *Severity:* `{{ .Labels.severity }}`

        {{- end }}

        {{- if .Labels.cluster }}

        *Cluster:*  {{ .Labels.cluster }}

        {{- end }}

        {{- if .Annotations.summary }}

        *Summary:* {{ .Annotations.summary }}

        {{- end }}

        {{- if .Annotations.message }}

        *Message:* {{ .Annotations.message }}

        {{- end }}

        {{- if .Annotations.description }}

        *Description:* {{ .Annotations.description }}

        {{- end }}

        {{- if .Annotations.runbook_url }}

        *Runbook URL:* <{{ .Annotations.runbook_url }}|:spiral_note_pad:>

        {{- end }}

        {{- with .Labels }}

        {{- with .Remove (stringSlice "alertname" "severity" "cluster") }}

        {{- if gt (len .) 0 }}

        *Additional Labels:*
          {{- range .SortedPairs }}
          • *{{ .Name }}:* `{{ .Value }}`
          {{- end }}
        {{- end }}

        {{- end }}

        {{- end }}

        {{- with .Annotations }}

        {{- with .Remove (stringSlice "summary" "message" "description"
        "runbook_url") }}

        {{- if gt (len .) 0 }}

        *Additional Annotations:*
          {{- range .SortedPairs }}
          • *{{ .Name }}:* `{{ .Value }}`
          {{- end }}
        {{- end }}

        {{- end }}

        {{- end }}

        {{- end -}}
    alertmanagerSpec:
      alertmanagerConfigSelector:
        matchExpressions:
          - key: release
            operator: NotIn
            values:
              - rancher-monitoring
      alertmanagerConfigNamespaceSelector: {}
      #alertmanagerConfigNamespaceSelector:
      #  matchLabels:
      #    "field.cattle.io/projectId": *projectId
      clusterAdvertiseAddress: false
      externalUrl:
      forceEnableClusterMode: false
      image:
        registry: mtr.devops.telekom.de
        repository: kubeprometheusstack/alertmanager
        tag: v0.27.0
      listenLocal: false
      logFormat: logfmt
      logLevel: info
      replicas: 1
      retention: 120h
      storage: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: gluster
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 50Gi
      #     selector: {}
      routePrefix: /
      resources:
        limits:
          memory: 750Mi
          cpu: 800m
        requests:
          memory: 200Mi
          cpu: 100m
      paused: false
      securityContext:
        fsGroup: 2000
        supplementalGroups:
          - 1000
      volumes: []
      volumeMounts: []
  global:
    rbac:
      create: false
      createAggregateClusterRoles: false
      pspEnabled: false
  grafana:
    adminPassword: prom-operator
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      privileged: false
      runAsUser: 472
      runAsGroup: 472
      readOnlyRootFilesystem: true
    createConfigmap: true
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-operated:9090
            access: proxy
            isDefault: true
    defaultDashboardsEnabled: false
    defaultDashboardsTimezone: browser
    enabled: true
    extraContainers: |
      - name: grafana-proxy
        args:
        - nginx
        - -g
        - daemon off;
        - -c
        - /nginx/nginx.conf
        image: mtr.devops.telekom.de/kubeprometheusstack/nginx:1.23.2-alpine
        ports:
        - containerPort: 8080
          name: nginx-http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsUser: 101
          runAsGroup: 101
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /nginx
          name: grafana-nginx
        - mountPath: /var/cache/nginx
          name: nginx-home
    extraContainerVolumes:
      - name: nginx-home
        emptyDir: {}
      - name: grafana-nginx
        configMap:
          name: nginx-proxy-config-project-monitoring-grafana
          items:
            - key: nginx.conf
              mode: 438
              path: nginx.conf
    forceDeployDatasources: true
    forceDeployDashboards: true
    fullnameOverride: project-monitoring-grafana
    grafana.ini:
      analytics:
        check_for_updates: false
      users:
        auto_assign_org_role: Viewer
      auth:
        disable_login_form: false
      auth.anonymous:
        enabled: false
        org_role: Viewer
      auth.basic:
        enabled: false
      security:
        # Required to embed dashboards in Rancher Cluster Overview Dashboard on Cluster Explorer
        allow_embedding: true
      log:
        level: info
    image:
      repository: mtr.devops.telekom.de/kubeprometheusstack/grafana
      tag: 10.4.1
    initChownData:
      enabled: false
    namespaceOverride: ""
    nameOverride: project-monitoring-grafana
    rbac:
      create: false
      namespaced: true
      pspEnabled: false
    resources:
      limits:
        memory: 600Mi
        cpu: 600m
      requests:
        memory: 200Mi
        cpu: 200m
    serviceAccount:
      create: false
      name: project-monitoring
    securityContext:
      fsGroup: 472
      runAsUser: 472
      runAsGroup: 472
      supplementalGroups:
        - 472
    sidecar:
      image:
        repository: mtr.devops.telekom.de/kubeprometheusstack/k8s-sidecar
        tag: 1.25.2
      plugins:
        searchNamespace: ""
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 50Mi
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsUser: 472
        runAsGroup: 472
        privileged: false
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        annotations: {}
        multicluster:
          global:
            enabled: false
          etcd:
            enabled: false
        provider:
          allowUiUpdates: false
        searchNamespace: ""
      datasources:
        createPrometheusReplicasDatasources: false
        defaultDatasourceEnabled: false
        enabled: true
        label: grafana_datasource
        labelValue: "1"
        searchNamespace: ""
    serviceMonitor:
      enabled: true
      path: "/metrics"
      interval: "30s"
      scheme: http
      scrapeTimeout: 30s
    service:
      portName: nginx-http
      port: 80
      targetPort: 8080
    testFramework:
      enabled: false
    ingress:
      enabled: true
      hosts:
        - grafana.caas-t03.telekom.de
    persistence:
      enabled: true
      size:    "20Gi",
    additionalDataSources: []
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  kubeControllerManager:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  kube-state-metrics:
    rbac:
      create: false
    releaseLabel: false
    prometheus:
      monitor:
        enabled: false
        honorLabels: false
    selfMonitor:
      enabled: false
  nodeExporter:
    enabled: false
  prometheus-node-exporter:
    prometheus:
      monitor:
        enabled: false
    releaseLabel: false
    rbac:
      pspEnabled: false
  prometheusOperator:
    enabled: false
  prometheus:
    enabled: true
    ingress:
      enabled: false
      annotations: {}
      labels: {}
      hosts: []
      paths: []
      tls: []
    ingressPerReplica:
      enabled: false
    prometheusSpec:
      additionalRemoteRead: []
      additionalRemoteWrite: []
      additionalScrapeConfigs:
        - job_name: "federate"
          scrape_interval: 30s
          honor_labels: true
          metrics_path: "/federate"
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          static_configs:
            - targets:
                - rancher-monitoring-prometheus.cattle-monitoring-system.svc:9091
          params:
            "match[]":
              - '{__name__=~".+"}'
      apiserverConfig: {}
      disableCompaction: false
      enableAdminAPI: false
      evaluationInterval: "30s"
      externalLabels: {}
      externalUrl: ""
      excludedFromEnforcement: []
      enforcedNamespaceLabel: ""
      enforcedLabelLimit: false
      enforcedLabelNameLengthLimit: false
      enforcedLabelValueLengthLimit: false
      enforcedSampleLimit: false
      enforcedTargetLimit: false
      enableRemoteWriteReceiver: false
      image:
        registry: mtr.devops.telekom.de
        repository: kubeprometheusstack/prometheus
        tag: v2.51.2
      ignoreNamespaceSelectors: false
      listenLocal: false
      logFormat: logfmt
      logLevel: info
      overrideHonorLabels: false
      overrideHonorTimestamps: false
      portName: "http-web"
      prometheusRulesExcludedFromEnforce: []
      prometheusExternalLabelName: ""
      prometheusExternalLabelNameClear: false
      podAntiAffinityTopologyKey: kubernetes.io/hostname
      podMonitorSelector:
        matchExpressions:
          - key: release
            operator: NotIn
            values:
              - rancher-monitoring
      podMonitorNamespaceSelector: {}
      #podMonitorNamespaceSelector:
      #  matchLabels:
      #    "field.cattle.io/projectId": *projectId
      #probeNamespaceSelector:
      #  matchLabels:
      #    "field.cattle.io/projectId": *projectId
      paused: false
      queryLogFile: false
      query: {}
      replicas: 1
      remoteRead: []
      remoteWrite: []
      remoteWriteDashboards: false
      resources:
        limits:
          memory: 1000Mi
          cpu: 1000m
        requests:
          memory: 400Mi
          cpu: 400m
      retention: 10d
      #retentionSize: ""
      routePrefix: /
      replicaExternalLabelName: ""
      replicaExternalLabelNameClear: false
      ruleNamespaceSelector: {}
      #ruleNamespaceSelector:
      #  matchLabels:
      #    "field.cattle.io/projectId": *projectId
      ruleSelector:
        matchExpressions:
          - key: release
            operator: NotIn
            values:
              - rancher-monitoring
      scrapeInterval: "30s"
      scrapeTimeout: "10s"
      securityContext:
        fsGroup: 2000
        supplementalGroups:
          - 1000
      serviceMonitorSelector:
        matchExpressions:
          - key: release
            operator: NotIn
            values:
              - rancher-monitoring
      serviceMonitorNamespaceSelector: {}
      #serviceMonitorNamespaceSelector:
      #  matchLabels:
      #    "field.cattle.io/projectId": *projectId
      shards: 1
      storageSpec: {}
      ## Using PersistentVolumeClaim
      ##
      #  volumeClaimTemplate:
      #    spec:
      #      storageClassName: gluster
      #      accessModes: ["ReadWriteOnce"]
      #      resources:
      #        requests:
      #          storage: 50Gi
      #    selector: {}
      ## Using tmpfs volume
      ##
      #  emptyDir:
      #    medium: Memory
      tsdb:
        outOfOrderTimeWindow: 5m
      volumes: []
      volumeMounts: []
      walCompression: true
    serviceAccount:
      create: false
      name: project-monitoring
    service:
      annotations: {}
      clusterIP: ""
      externalIPs: []
      externalTrafficPolicy: Cluster
      labels: {}
      port: 9090
      publishNotReadyAddresses: false
      targetPort: 9090
      type: ClusterIP
    servicePerReplica:
      enabled: false
    serviceMonitor:
      interval: "30s"
      selfMonitor: true
      scheme: ""
      tlsConfig: {}
      bearerTokenFile:
      metricRelabelings: []
      relabelings: []
  thanosRuler:
    enabled: false
```

</details>

Have i misconfigured something?
